name: Workflow

on: pull_request

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install
        run: npm ci

      - name: Tests
        run: npm run test -- --exclude=**/cypress/e2e/login.spec.ts
        

  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install
        run: npm ci
        
      - name: Tests e2e
        run: npm run test:e2e:ci